---


- name: K3s uninstall playbook
  hosts: master
  become: yes


  tasks:
   - name: Uninstall script
     shell: sh /usr/local/bin/k3s-uninstall.sh
   

   - name: Check service status
     service:
      name: k3s.service
      enabled: false    
